table dim_date
	lineageTag: 4f44fab6-aebb-4be8-b522-13190e0d9868

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: 8a907362-1249-4af9-983c-a34313bf31e8
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: df1a673e-050a-4862-9871-a4e14ecbc3d3
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 71e809eb-2671-4db0-a5c3-f1688ab313d4
			defaultHierarchy: LocalDateTable_6075b135-d12c-4079-9761-b26c39fe229b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		formatString: 0
		lineageTag: 93f99a3a-0f18-47ee-9ea5-9094318b5e26
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: aba5bdbf-8a36-4b53-b65e-7059856949dc
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: b275ca17-aceb-41e2-81e2-7f3977f8f8c4
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 14f929b5-d086-4c67-a671-2c87bd4d44f6
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

	column week
		dataType: int64
		formatString: 0
		lineageTag: f8f5d360-5ec4-422d-809d-41c793a1582c
		summarizeBy: sum
		sourceColumn: week

		annotation SummarizationSetBy = Automatic

	column day
		dataType: int64
		formatString: 0
		lineageTag: a5c90322-7ef2-4de9-a749-405d30913092
		summarizeBy: sum
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column day_of_week
		dataType: int64
		formatString: 0
		lineageTag: 8309e901-5f4f-4d50-bd39-5cf8abbb5f90
		summarizeBy: sum
		sourceColumn: day_of_week

		annotation SummarizationSetBy = Automatic

	column day_name
		dataType: string
		lineageTag: 224ab968-1c1d-4001-bc95-5ebd717388c6
		summarizeBy: none
		sourceColumn: day_name

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: 6db0451f-f5ae-4d4f-83f1-3635916d45e1
		summarizeBy: sum
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		source =
				let
				    Source = Folder,
				    #"C:\Users\NIthya Sree\Downloads\powerbi\_dim_date csv" = Source{[#"Folder Path"=folder_path,Name="dim_date.csv"]}[Content],
				    #"Imported CSV" = Csv.Document(#"C:\Users\NIthya Sree\Downloads\powerbi\_dim_date csv",[Delimiter=",", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"date_key", Int64.Type}, {"date", type date}, {"year", Int64.Type}, {"quarter", Int64.Type}, {"month", Int64.Type}, {"month_name", type text}, {"week", Int64.Type}, {"day", Int64.Type}, {"day_of_week", Int64.Type}, {"day_name", type text}, {"is_weekend", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

