table fact_inventory
	lineageTag: e2e16879-9602-450b-a3a8-6f59e6772329

	column inventory_id
		dataType: int64
		formatString: 0
		lineageTag: 726cee59-a4d4-4295-bb1d-ec801ebee3b0
		summarizeBy: sum
		sourceColumn: inventory_id

		annotation SummarizationSetBy = Automatic

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: 883ad2a3-950e-49bc-a1a3-a4971a43a18a
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: 7b5e9116-6c5a-4104-8c04-3faf5ff4b44b
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column facility_id
		dataType: int64
		formatString: 0
		lineageTag: 4c67e876-6d01-4c4a-997f-050e797f20d1
		summarizeBy: sum
		sourceColumn: facility_id

		annotation SummarizationSetBy = Automatic

	column stock_level
		dataType: int64
		formatString: 0
		lineageTag: dfb18035-eddb-4b5c-b912-6dd9cb53e5f7
		summarizeBy: sum
		sourceColumn: stock_level

		annotation SummarizationSetBy = Automatic

	column safety_stock_level
		dataType: int64
		formatString: 0
		lineageTag: 1639746b-822f-4f08-b065-a98a63ce6dae
		summarizeBy: sum
		sourceColumn: safety_stock_level

		annotation SummarizationSetBy = Automatic

	column reorder_point
		dataType: int64
		formatString: 0
		lineageTag: 115b8090-3b90-4180-a12f-abcd6c2b80c8
		summarizeBy: sum
		sourceColumn: reorder_point

		annotation SummarizationSetBy = Automatic

	partition fact_inventory = m
		mode: import
		source =
				let
				    Source = Folder,
				    #"C:\Users\NIthya Sree\Downloads\powerbi\_fact_inventory csv" = Source{[#"Folder Path"=folder_path,Name="fact_inventory.csv"]}[Content],
				    #"Imported CSV" = Csv.Document(#"C:\Users\NIthya Sree\Downloads\powerbi\_fact_inventory csv",[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"inventory_id", Int64.Type}, {"date_key", Int64.Type}, {"product_id", Int64.Type}, {"facility_id", Int64.Type}, {"stock_level", Int64.Type}, {"safety_stock_level", Int64.Type}, {"reorder_point", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

